masters/apps/courses/urls.py
from django.urls import path
from .views import CourseListView,CourseDetailView, LessonView, CourseEnrollmentView
urlpatterns = [
    path('', CourseListView.as_view(), name='course_list'),
    path('<str:slug>/', CourseDetailView.as_view(), name='course_detail'),
    path('<str:course>/items/<str:item>/', LessonView.as_view(), name="lesson"),
    path('<str:course>/enroll/', CourseEnrollmentView.as_view(), name="enrollment")
]

masters/apps/statics/urls.py
from django.urls import path
from .views import AboutUsView,ContactView,ComplaintView
urlpatterns = [
    path('about',AboutUsView.as_view(), name="about_us"),
    path('contact',ComplaintView.as_view(), name="contact_us"),
    path('complaint',ComplaintView.as_view(), name="complaint"),
]

masters/apps/users/urls.py
from .views import DevLoginView, DevSignupView, DevLogoutView, ProfileCourses, ProfileDashboardView, EditProfile
from django.urls import path
from django.contrib.auth import views

urlpatterns = [
    path('login/', DevLoginView.as_view(), name='login'),
    path('register/', DevSignupView.as_view(), name='register'),
    path('logout/', DevLogoutView.as_view(), name='logout'),
    #
    # path('password_change/', views.PasswordChangeView.as_view(), name='password_change'),
    # path('password_change/done/', views.PasswordChangeDoneView.as_view(), name='password_change_done'),
    #
    path('password_reset/', views.PasswordResetView.as_view(), name='password_reset'),
    path('password_reset/done/', views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset/done/', views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),

    path('profile/', ProfileDashboardView.as_view(), name="profile_dashboard"),
    path('profile/courses', ProfileCourses.as_view(), name="profile_courses"),
    path('profile/edit', EditProfile.as_view(), name="profile_edit")
]

masters/urls.py
from django.conf import settings
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from django.urls import path, include
from masters.apps.statics.views import home_view
from django.conf.urls.static import static
from masters.apps.courses import sitemaps as course_sitemaps
from masters.apps.statics import  sitemaps as static_sitemaps

urlpatterns = [
    path('', home_view, name="home"),
    path('PJzclOrm/', admin.site.urls),
    path('auth/', include('social_django.urls', namespace='social')),
    path('accounts/', include('masters.apps.users.urls')),
    path('courses/', include('masters.apps.courses.urls')),
    path('statics/', include('masters.apps.statics.urls'))
]

sitemaps = {
    'static': static_sitemaps.StaticSitemap,
    'courses': course_sitemaps.CourseSitemap,
    'lessons': course_sitemaps.CourseLessonSitemap
}

urlpatterns += [
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap')
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
# else:
#     urlpatterns += [
#         re_path(r'^%s(?P<path>.*)$' % re.escape(settings.MEDIA_URL.lstrip('/')), ServeProtectedMedia.as_view())
#     ]

masters/apps/courses/models.py
from django.db import models
from django.urls import reverse
from django.utils import timezone
from django.utils.translation import gettext_noop, gettext_lazy as _
from django.template.defaultfilters import slugify
from django.contrib.auth import get_user_model
from django.contrib.auth import get_user_model
from .utils import get_file_path

User = get_user_model()


# Create your models here.
class CourseCategory(models.Model):
    title = models.CharField(_("Title"), max_length=500, blank=False)
    slug = models.SlugField(_('Slug'), allow_unicode=True, max_length=255, unique=True)
    weight = models.SmallIntegerField(_("Weight"), null=True, blank=True)

    def __str__(self):
        return self.title

    class Meta:
        ordering = ['weight']
        verbose_name = _("Course Category")
        verbose_name_plural = _("Course Categories")


class Course(models.Model):
    title = models.CharField(_("Title"), max_length=500, blank=False)
    slug = models.SlugField(_('Slug'), allow_unicode=True, max_length=255, unique=True)
    abstract = models.TextField(_("Abstract"), max_length=2048, blank=True)
    description = models.TextField(verbose_name=_("Description"), blank=True)
    authors = models.ManyToManyField(get_user_model())
    categories = models.ManyToManyField(CourseCategory)
    pre_requirements = models.ManyToManyField("Course",related_name="prereqs", blank=True)
    thumbnail = models.ImageField(_("Thumbnail"), upload_to="thumbnails/", null=True, blank=True)
    is_free = models.BooleanField(_("Is Free"), default=False)
    price = models.IntegerField(_("Price"), null=True, blank=True)
    time_duration = models.CharField(_("Time Duration"), blank=True, max_length=100)
    level = models.CharField(_("Level"), max_length=100, blank=True)
    suggested_to = models.TextField(_("Suggested To"), blank=True)
    published = models.BooleanField(_("Published"), default=True)
    in_progress = models.BooleanField(_("in progress"), default=False)
    created = models.DateTimeField(_("Created"), auto_now_add=True)
    updated = models.DateTimeField(_("Updated"), auto_now=True)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('course_detail', kwargs={'slug': self.slug})

    class Meta:
        ordering = ['-created']
        verbose_name = _("Course")
        verbose_name_plural = _("Courses")


class CourseKeyPoint(models.Model):
    course = models.ForeignKey(Course, verbose_name=_("Course"), on_delete=models.CASCADE)
    title = models.CharField(_("Title"), max_length=500, blank=False)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = _("Course Key Point")
        verbose_name_plural = _("Course Key Points")


class CourseSection(models.Model):
    course = models.ForeignKey(Course, verbose_name=_("Course"), on_delete=models.CASCADE)
    title = models.CharField(_("Title"), max_length=500, blank=False)
    weight = models.SmallIntegerField(_("Weight"), null=True, blank=True)

    def __str__(self):
        return self.title

    class Meta:
        ordering = ['weight']
        verbose_name = _("Course Section")
        verbose_name_plural = _("Course Sections")


class CourseSectionItem(models.Model):
    VIDEO = 'video'
    ITEM_TYPE_CHOICE = (
        (VIDEO, _("Video"),),
    )
    section = models.ForeignKey(CourseSection, verbose_name=_("Course Sections"), on_delete=models.CASCADE)
    title = models.CharField(_("Title"), max_length=500, blank=False)
    description = models.TextField(verbose_name=_("Description"), blank=True)
    slug = models.SlugField(_('Slug'), allow_unicode=True, max_length=255, unique=True)
    item_type = models.CharField(_("Item Type"), max_length=255, choices=ITEM_TYPE_CHOICE, default=VIDEO)
    is_free = models.BooleanField(_("Is Free"), default=False)
    need_enroll = models.BooleanField(_("need enrolled"), default=True)
    public_url = models.CharField(_("Public Url"), max_length=1024, blank=True)
    duration = models.CharField(_("Duration", ), max_length=128, blank=True)
    weight = models.SmallIntegerField(_("Weight"), null=True, blank=True)
    file_url = models.FileField(_('File'), upload_to=get_file_path, null=True, blank=True)
    published = models.BooleanField(_("Published"), default=True)
    created = models.DateTimeField(_("Created"), auto_now_add=True)
    updated = models.DateTimeField(_("Updated"), auto_now=True)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('lesson', kwargs={'course': self.section.course.slug, 'item': self.slug})

    class Meta:
        ordering = ['weight']
        verbose_name = _("Course Section Item")
        verbose_name_plural = _("Course Section Items")


class CourseEnrollment(models.Model):
    MANUAL = 'manual'
    ENROLL_TYPE_CHOICE = (
        (MANUAL, _("Manual"),),
    )
    user = models.ForeignKey(User, verbose_name=_("User"), on_delete=models.CASCADE)
    course = models.ForeignKey(Course, verbose_name=_("Course"), on_delete=models.CASCADE)
    enroll_date = models.DateTimeField(_("Enroll Date"), default=timezone.now)
    enroll_type = models.CharField(_("Enroll Type"), max_length=25, choices=ENROLL_TYPE_CHOICE, default=MANUAL)

    class Meta:
        unique_together = ('user', 'course',)
        ordering = ['-enroll_date']
        verbose_name = _("Course Enrollment")
        verbose_name_plural = _("Course Enrollments")

masters/apps/statics/models.py
from django.db import models

# Create your models here.

masters/apps/users/forms.py
from django import forms
from django.contrib.auth import (
    get_user_model, password_validation,
)
from django.contrib.auth.forms import UsernameField
from django.utils.translation import gettext_lazy as _

UserModel = get_user_model()


class SignUpForm(forms.ModelForm):
    """
    A form that creates a user, with no privileges, from the given username and
    password.
    """
    error_messages = {
        'password_mismatch': _("The two password fields didn't match."),
    }
    email = forms.CharField(
        label="پست الکترونیک ",
        required=True,
        widget=forms.EmailInput(attrs={'class': 'form-control',
                                       'placeholder': 'ایمیل خود را به عنوان نام کاربری در این وب سایت وارد نمایید'}),

    )
    password1 = forms.CharField(
        label="کلمه عبور",
        strip=False,
        widget=forms.PasswordInput(
            attrs={'class': 'form-control', 'placeholder': 'کلمه عبور  مورد نظر خود را وارد نمایید'}),
        help_text=password_validation.password_validators_help_text_html(),
    )
    password2 = forms.CharField(
        label="تایپ مجدد کلمه عبور",
        widget=forms.PasswordInput(
            attrs={'class': 'form-control', 'placeholder': 'کلمه عبور  مورد نظر خود را  مجددا وارد نمایید'}),
        strip=False,
        help_text=_("Enter the same password as before, for verification."),
    )

    class Meta:
        model = UserModel
        fields = ("email",)
        field_classes = {'email': UsernameField}

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        if self._meta.model.USERNAME_FIELD in self.fields:
            self.fields[self._meta.model.USERNAME_FIELD].widget.attrs.update({'autofocus': True})

    def clean_password2(self):
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError(
                self.error_messages['password_mismatch'],
                code='password_mismatch',
            )
        return password2

    def _post_clean(self):
        super()._post_clean()
        # Validate the password after self.instance is updated with form data
        # by super().
        password = self.cleaned_data.get('password2')
        if password:
            try:
                password_validation.validate_password(password, self.instance)
            except forms.ValidationError as error:
                self.add_error('password2', error)

    def save(self, commit=True):
        user = super().save(commit=False)
        user.set_password(self.cleaned_data["password1"])
        if commit:
            user.save()
        return user

masters/apps/courses/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse
from django.views import View
from django.views.generic import ListView, DetailView
from .models import Course, CourseCategory, CourseSectionItem, CourseEnrollment


# Create your views here.


class CourseListView(ListView):
    template_name = "courses/course_list.html"
    model = Course

    def get_queryset(self):
        if self.request.GET.get("category"):
            slug = self.request.GET["category"]
            return Course.objects.all().filter(published=True, categories__slug=slug)
        else:
            return Course.objects.all().filter(published=True)

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(CourseListView, self).get_context_data(**kwargs)
        context["categories"] = CourseCategory.objects.all()
        return context


class CourseDetailView(DetailView):
    template_name = "courses/course_detail.html"
    model = Course

    def get_context_data(self, **kwargs):
        context = super(CourseDetailView, self).get_context_data(**kwargs)

        if self.request.user.is_authenticated and CourseEnrollment.objects.all().filter(user_id=self.request.user.id,
                                                                                        course=kwargs.get(
                                                                                                'object')).exists():
            context["enrolled"] = True
        else:
            context["enrolled"] = False

        return context


class LessonView(View):
    def get(self, request, course, item):
        course = get_object_or_404(Course, slug=course)
        context = {
            'course': course,
            'item': get_object_or_404(CourseSectionItem, slug=item),
            'enrolled': CourseEnrollment.objects.filter(course_id=course.id, user_id=request.user.id).exists()
        }
        return render(request, "courses/lesson.html", context)


class CourseEnrollmentView(LoginRequiredMixin, View):
    def get(self, request, course):
        course = get_object_or_404(Course, slug=course)
        user = request.user
        enroll = CourseEnrollment(user_id=user.id, course_id=course.id)
        enroll.save()
        return redirect(reverse('lesson', kwargs={'course': course.slug,  'item': course.coursesection_set.all()[0].coursesectionitem_set.all()[0].slug}))

masters/apps/statics/views.py
from django.shortcuts import render
from django.views import View

from masters.apps.courses.models import Course


# Create your views here.
def home_view(request):
    context = {
        'courses': Course.objects.all().filter(published=True)
    }
    return render(request, 'statics/home.html', context)


class AboutUsView(View):
    def get(self, request):
        return render(request, 'statics/aboutus.html')


class ContactView(View):
    def get(self, request):
        return render(request, 'statics/contact.html')

class ComplaintView(View):
    def get(self, request):
        return render(request, 'statics/complaint.html')

masters/apps/users/views.py
from django.contrib.auth import authenticate, login
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import LoginView, LogoutView
from django.shortcuts import render, redirect, get_object_or_404
from django.views import View
from django.contrib.auth import get_user_model
from .forms import SignUpForm
from masters.apps.courses.models import CourseEnrollment
User = get_user_model()

class DevLoginView(LoginView):
    template_name = 'users/login.html'
    redirect_authenticated_user = True


class DevSignupView(View):
    def get(self, request):
        form = SignUpForm()
        return render(request, 'users/signup.html', {'form': form})

    def post(self, request):
        form = SignUpForm(request.POST)
        if form.is_valid():
            form.save()
            email = form.cleaned_data.get('email')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=email, password=raw_password)
            login(request, user)
            return redirect('profile_dashboard')
        return render(request, 'users/signup.html', {'form': form})


class DevLogoutView(LogoutView):
    template_name = 'users/logout.html'


class ProfileDashboardView(LoginRequiredMixin,View):
    def get(self, request):
        return render(request, 'users/profile_dashboard.html')


class ProfileCourses(LoginRequiredMixin,View):
    def get(self, request):
        context = {
            'courses': CourseEnrollment.objects.all().filter(user_id=request.user.id)
        }
        return render(request, 'users/profile_courses.html', context)


class EditProfile(LoginRequiredMixin,View):
    def get(self, request):
        return render(request, 'users/profile_edit.html')

    def post(self, request):
        user = get_object_or_404(User, pk=request.user.id)
        user.first_name = request.POST["first_name"]
        user.last_name = request.POST["last_name"]
        user.save()
        request.user = user
        return render(request, 'users/profile_edit.html')

masters/templates/statics/home.html
{%  extends "base.html" %}
{% load static%}


{% block content %}

     <!-- Header -->



        <!-- // END Header -->

        <!-- Header Layout Content -->
        <div class="mdk-header-layout__content page-content ">


            <div class="mdk-box mdk-box--bg-gradient-primary bg-dark js-mdk-box position-relative overflow-hidden mb-0" data-effects="parallax-background blend-background">
                <div class="mdk-box__bg">
                    <div class="mdk-box__bg-front" style="background-image: url({% static "images/1280_work-station-straight-on-view.jpg" %});"></div>
                </div>
                <div class="mdk-box__content">
                    <div class="container page__container py-64pt py-md-112pt">
                        <div class="row align-items-center text-center text-md-left">
                            <div class="col-md-6 col-lg-5 order-1 order-md-0">
                                <h1 class="text-white">یادگیری  توسعه نرم افزار</h1>
                                <p class="lead mb-32pt mb-lg-48pt text-white">آموزش استک های مدرن تکنولوژی نرم افزار و زبان های برنامه نویسی نوین برای توسعه دهندگان نرم افزار</p>
                                <a href="{% url "course_list" %}" class="btn btn-lg btn-white btn--raised mb-16pt">مرور دوره ها</a>
                            </div>
                            <div class="col-md-6 col-lg-7 order-0 order-md-1 text-center mb-32pt mb-md-0">
                                <img src="{% static "images/macbook-dark.png" %}" alt="macbook" class="home-macbook">
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <div class="navbar-submenu py-16pt py-sm-24pt py-md-32pt ">
                <div class="container page__container">
                    <div class="row align-items-center">
                        <div class="d-flex col-md align-items-center border-bottom border-md-0 mb-16pt mb-md-0 pb-16pt pb-md-0">
                            <div class="rounded-circle border border-secondary w-64 h-64 d-inline-flex align-items-center justify-content-center mr-16pt">
                                <i class="material-icons text-secondary">subscriptions</i>
                            </div>
                            <div class="flex">
                                <p class="mb-0"><strong>تنوع در دوره ها</strong></p>
                                <p class="text-70 mb-0">تنوع در زبان ها و تکنولوژی ها</p>
                            </div>
                        </div>
                        <div class="d-flex col-md align-items-center border-bottom border-md-0 mb-16pt mb-md-0 pb-16pt pb-md-0">
                            <div class="rounded-circle border border-secondary w-64 h-64 d-inline-flex align-items-center justify-content-center mr-16pt">
                                <i class="material-icons text-secondary">verified_user</i>
                            </div>
                            <div class="flex">
                                <p class="mb-0"><strong>برنامه نویسان باتجربه</strong></p>
                                <p class="text-70 mb-0">تدریس توسط برنامه نویسان مجرب</p>
                            </div>
                        </div>
                        <div class="d-flex col-md align-items-center">
                            <div class="rounded-circle border border-secondary w-64 h-64 d-inline-flex align-items-center justify-content-center mr-16pt">
                                <i class="material-icons text-secondary">update</i>
                            </div>
                            <div class="flex">
                                <p class="mb-0"><strong>دسترسی سریع</strong></p>
                                <p class="text-70 mb-0">دسترسی سریع و آسان به دوره ها</p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <div class="page-section border-bottom-2">
                <div class="container page__container">
                    <div class="row align-items-end mb-16pt mb-md-32pt">
                        <div class="col-md-auto mb-32pt mb-md-0">
                            <div class="page-headline page-headline--title text-center text-md-left p-0">
                                <h2>جدیدترین دوره ها</h2>
                            </div>
                        </div>
                        <div class="col-md text-center text-md-right d-flex justify-content-md-end align-items-center flex-wrap" style="white-space: nowrap;">
                            <h5 class="mr-24pt mb-md-0 d-md-inline-block"> موضوع های محبوب</h5>
                            <a href="library-development.html" class="chip mb-16pt mb-md-0 chip-outline-secondary">Kotlin</a>
                            <a href="library-development.html" class="chip mb-16pt mb-md-0 chip-outline-secondary">Swift</a>
                        </div>
                    </div>


                    <div class="row">

                        {% for course in courses %}
                        <div class="col-sm-6 col-md-4 col-lg-3">

                            <div class="card card--elevated card-course overlay js-overlay mdk-reveal js-mdk-reveal " data-partial-height="40" data-toggle="popover" data-trigger="click">


                                <a href="{% url "course_detail" slug=course.slug %}" class="js-image" data-position="center">
                                    <img src="{{ course.thumbnail.url }}" alt="course">
                                    <span class="overlay__content">
                                        <span class="overlay__action d-flex flex-column text-center">
                                            <i class="material-icons">play_circle_outline</i>
                                            <small>بررسی دوره</small>
                                        </span>
                                    </span>
                                </a>

                                <span class="corner-ribbon corner-ribbon--default-right-top corner-ribbon--shadow bg-accent text-white">جدید</span>

                                <div class="mdk-reveal__content">
                                    <div class="card-body">
                                        <div class="d-flex">
                                            <div class="flex">
                                                <a class="card-title" href="{% url "course_detail" slug=course.slug %}">{{ course.title }}</a>
                                                 {% for author in course.authors.all %}
                                                    <small class="text-50 font-weight-bold mb-4pt">{{ author.get_full_name}}</small>
                                                 {% endfor %}
                                            </div>
                                        </div>
                                        <div class="d-flex">
                                            <div class="rating flex">

                                            </div>
                                            <small class="text-50">{{ course.time_duration }}</small>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="popoverContainer d-none">
                                <div class="media">
                                    <div class="media-left">
                                        <img src="{{ course.thumbnail.url }}" width="40" height="40" alt="Angular" class="rounded">
                                    </div>
                                    <div class="media-body">
                                        <div class="card-title mb-0">{{ course.title }}</div>
                                        <p class="lh-1 mb-0">
                                            {% for author in course.authors.all %}
                                            <span class="text-black-50 small font-weight-bold">{{ author.get_full_name}}</span>
                                            {% endfor %}
                                        </p>
                                    </div>
                                </div>

                                <p class="my-12pt text-black-70">{{ course.abstract }}</p>

                                <div class="mb-16pt">

                                    {% for keypoint in course.coursekeypoint_set.all %}
                                    <div class="d-flex align-items-center">
                                        <span class="material-icons icon-16pt text-black-50 mr-8pt">check</span>
                                        <p class="flex text-black-50 lh-1 mb-0"><small>{{ keypoint.title }}</small></p>
                                    </div>
                                    {% endfor %}

                                </div>

                                <div class="row align-items-center">
                                    <div class="col-auto">
                                        <div class="d-flex align-items-center mb-4pt">
                                            <span class="material-icons icon-16pt text-black-50 mr-4pt">access_time</span>
                                            <p class="flex text-black-50 lh-1 mb-0"><small> {{ course.time_duration }}</small></p>
                                        </div>
                                        <div class="d-flex align-items-center">
                                            <span class="material-icons icon-16pt text-black-50 mr-4pt">assessment</span>
                                            <p class="flex text-black-50 lh-1 mb-0"><small>{{ course.level }}</small></p>
                                        </div>
                                    </div>
                                    <div class="col text-right">
                                        <a href="{% url "course_detail" slug=course.slug %}" class="btn btn-primary">مشاهده دوره</a>
                                    </div>
                                </div>

                            </div>

                        </div>
                        {% endfor %}


                    </div>
                    <div class="pt-md-16pt text-center">
                        <a href="{% url "course_list" %}" class="btn btn-outline-secondary">مرور دوره ها</a>
                    </div>
                </div>
            </div>

        </div>
        <!-- // END Header Layout Content -->

    <!-- // END Header Layout -->
{% endblock %}